name: New Lint Rule Request
description: request a new lint rule
title: "[new rule]: "
labels: ["linter", "rule"]
assignees: jianyxi,ruoxuanwang
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new rule form!
  - type: textarea
    id: lint rule description
    attributes:
      label: description ?
      description: describe the lint rule
      placeholder: please add some description for the lint rule
      value: ""
    validations:
      required: true
      
  - type: textarea
    id: swagger-example-related
    attributes:
      label: example ?
      description: add an example for this rule
      placeholder: please add some example for the lint rule
      value: ""
    validations:
      required: true
      
  - type: dropdown
    id: Category
    attributes:
      label: Category
      description: which 
      options:
        - SDK
        - ARM
        - Documentation
    validations:
      required: true
  - type: dropdown
    id: Severitylevel
    attributes:
      label: specify the severity level
      options:
        - Error
        - Warning
    validations:
      required: true
  - type: dropdown
    id: AppliesTo
    attributes:
      label: arm or dataplane or rpaas 
      multiple: true
      options:
        - Management plane API spec
        - Data plane API spec
        - RPaaS API spec
    validations:
      required: true
  - type: textarea
    id: howtofix
    attributes:
      label: how to fix 
      description: please descripe how to fix
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: the impact 
      description: what't the impact if breaking the rule
    validations:
      required: true
